export const OK_STATUS_CODE = 200
export const CREATED_CODE = 201
export const BAD_REQUEST_STATUS_CODE = 400
export const FORBIDDEN_STATUS_CODE = 403
export const NOT_FOUND_CODE = 404
export const UNPROCESSABLE_ENTITY_STATUS_CODE = 422